apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext-worker
  namespace: erpnext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erpnext-worker
  template:
    metadata:
      labels:
        app: erpnext-worker
    spec:
      containers:
      - name: worker
        image: frappe/erpnext:v14.65.1
        args: ["worker"]
        env:
        - name: MARIADB_HOST
          value: "mariadb"
        - name: REDIS_CACHE
          value: "redis:6379"
        - name: REDIS_QUEUE
          value: "redis:6379"
        - name: REDIS_SOCKETIO
          value: "redis:6379"
        volumeMounts:
        - name: sites-data
          mountPath: /home/frappe/frappe-bench/sites
      volumes:
      - name: sites-data
        persistentVolumeClaim:
          claimName: erpnext-sites-pvc
