# ERPNext v14.65.1 — OpenShift / GitOps (resmi chart: erpnext 8.0.65)
image:
  repository: image-registry.openshift-image-registry.svc:5000/erpnext/erpnext-tevkifat
  tag: v14.65.1
  pullPolicy: Always
serviceAccount:
  create: false

persistence:
  worker:
    enabled: true
    storageClass: erpnext-sites
    size: 15Gi
    accessModes:
      - ReadWriteOnce
  logs:
    enabled: false

mariadb-sts:
  enabled: true
  rootPassword: "prime"
  persistence:
    storageClass: erpnext-mariadb
    size: 20Gi
  myCnf: |
    [mysqld]
    skip-character-set-client-handshake
    skip-innodb-read-only-compressed
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci

mariadb-subchart:
  enabled: false
mariadb:
  enabled: false
  jobs:
  createSite:
    enabled: true
    forceCreate: false
    siteName: "erpnext.apps.ocp.local"
    adminPassword: "prime"
    installApps:
      - erpnext
    dbType: mariadb

nginx:
  defaultTopologySpread:
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway

worker:
  defaultTopologySpread:
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
